package org.lesson6.db.dao;

import org.lesson6.db.model.Categories;
import org.lesson6.db.model.CategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    long countByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int deleteByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int insert(Categories row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int insertSelective(Categories row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    List<Categories> selectByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    Categories selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int updateByExampleSelective(@Param("row") Categories row, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int updateByExample(@Param("row") Categories row, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int updateByPrimaryKeySelective(Categories row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated Tue Jul 26 00:43:23 MSK 2022
     */
    int updateByPrimaryKey(Categories row);
}