package org.lesson6.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lesson6.db.model.Products;
import org.lesson6.db.model.ProductsExample;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    long countByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int deleteByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int insert(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int insertSelective(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    List<Products> selectByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    Products selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int updateByExampleSelective(@Param("row") Products row, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int updateByExample(@Param("row") Products row, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int updateByPrimaryKeySelective(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Fri Aug 05 02:02:14 MSK 2022
     */
    int updateByPrimaryKey(Products row);
}